CREATE TABLE VENDA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID BIGINT,
    VENDEDOR_ID BIGINT,
    DATA_VENDA TIMESTAMP,
    VALOR_TOTAL DECIMAL(10,2),
    CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_VENDA_VENDEDOR FOREIGN KEY (VENDEDOR_ID) REFERENCES VENDEDOR(ID)
);