CREATE TABLE VENDA_PRODUTOS (
    VENDA_ID BIGINT NOT NULL,
    PRODUTOS_ID BIGINT NOT NULL,
    PRIMARY KEY (VENDA_ID, PRODUTOS_ID),
    CONSTRAINT FK_VENDA_PRODUTO_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID),
    CONSTRAINT FK_VENDA_PRODUTO_PRODUTO FOREIGN KEY (PRODUTOS_ID) REFERENCES PRODUTO(ID)
);
