CREATE TABLE VENDA_PRODUTO (
    VENDA_ID BIGINT NOT NULL,
    PRODUTO_ID BIGINT NOT NULL,
    PRIMARY KEY (VENDA_ID, PRODUTO_ID),
    CONSTRAINT FK_VENDA_PRODUTO_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID),
    CONSTRAINT FK_VENDA_PRODUTO_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);